name: Deploy to GitHub Pages

on:
  # Se ejecuta cada vez que haces un 'push' a la rama 'main'
  push:
    branches:
      - main
  # Te permite ejecutarlo manualmente desde la pesta침a Actions en GitHub
  workflow_dispatch:

# Permisos necesarios para que la acci칩n pueda escribir en GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v2
        # No necesitamos 'with:' si la configuraci칩n es est치ndar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4